<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Razorpay" Version="3.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
    <PackageReference Include="Typesense" Version="7.36.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecom.Api\AuthService.Api\AuthService.Api.csproj" />
    <ProjectReference Include="..\Ecom.Api\CartService.Api\CartService.Api.csproj" />
    <ProjectReference Include="..\Ecom.Api\CatalogService.Api\CatalogService.Api.csproj" />
    <ProjectReference Include="..\Ecom.Api\OrderService.APi\OrderService.APi.csproj" />
    <ProjectReference Include="..\Ecom.Api\PaymentService.Api\PaymentService.Api.csproj" />
    <ProjectReference Include="..\Ecom.Api\ReviewService.Api\ReviewService.Api.csproj" />
    <ProjectReference Include="..\Ecom.Application\Ecom.Application.csproj" />
    <ProjectReference Include="..\Ecom.Domain\Ecom.Domain.csproj" />
    <ProjectReference Include="..\Ecom.Gateway\Ecom.Gateway.csproj" />
    <ProjectReference Include="..\Ecom.Infrastructure\Ecom.Infrastructure.csproj" />
  </ItemGroup>

</Project>
